// Catálogo de histórias das obras do acervo (FrontEnd/public/acervo). A chave é o nome do
// arquivo sem ".jpg". Serve para a tela de "obras adquiridas": quem arremata uma peça
// cuja foto é uma dessas obras ganha a história dela, o contexto da época e o autor.
// (As peças da plataforma são reproduções de demonstração; o original está em "localAtual".)
export interface ObraCatalogo {
  titulo: string;
  artista: string;
  ano: string;
  movimento: string;
  localAtual: string;
  historia: string;
  contextoHistorico: string;
  contextoFilosofico: string;
  contextoSocial: string;
  curiosidade: string;
}

export const CATALOGO_OBRAS: Record<string, ObraCatalogo> = {
  'noite-estrelada': {
    titulo: 'A Noite Estrelada', artista: 'Vincent van Gogh', ano: '1889', movimento: 'Pós-impressionismo', localAtual: 'MoMA, Nova York',
    historia: 'Pintada em junho de 1889, do quarto do asilo de Saint-Rémy-de-Provence onde Van Gogh estava internado por vontade própria. O céu em turbilhão foi feito de memória; o vilarejo e o cipreste são invenções.',
    contextoHistorico: 'A França vivia a Belle Époque, com a Revolução Industrial transformando cidades e o Impressionismo já tendo rompido com a pintura acadêmica.',
    contextoFilosofico: 'Crescia o interesse pela experiência subjetiva: a emoção do artista passava a valer mais que a fidelidade à aparência.',
    contextoSocial: 'Van Gogh sofria de crises mentais, vendeu quase nada em vida e sobrevivia com a ajuda do irmão Theo.',
    curiosidade: 'O próprio artista considerava a tela um fracasso; hoje é uma das imagens mais reconhecidas do mundo.',
  },
  'moca-brinco-perola': {
    titulo: 'Moça com Brinco de Pérola', artista: 'Johannes Vermeer', ano: 'c. 1665', movimento: 'Barroco holandês', localAtual: 'Mauritshuis, Haia',
    historia: 'Uma "tronie", estudo de rosto e expressão, e não um retrato encomendado. A luz suave e o turbante azul feito com pigmento de lápis-lazúli fazem a moça parecer prestes a falar.',
    contextoHistorico: 'A jovem República Holandesa vivia a Era de Ouro: comércio marítimo, riqueza e um mercado de arte movido por burgueses, não pela Igreja.',
    contextoFilosofico: 'O racionalismo e a nova ciência (óptica, câmara escura) ensinavam a observar a luz com método.',
    contextoSocial: 'A pintura de gênero e de interiores agradava a uma classe média próspera que decorava as próprias casas.',
    curiosidade: 'Pouco se sabe sobre quem posou; Vermeer deixou cerca de 35 obras conhecidas.',
  },
  'impressao-nascer-do-sol': {
    titulo: 'Impressão, Nascer do Sol', artista: 'Claude Monet', ano: '1872', movimento: 'Impressionismo', localAtual: 'Museu Marmottan Monet, Paris',
    historia: 'Vista do porto de Le Havre ao amanhecer, pintada com pinceladas rápidas para captar a luz do instante. Ao ser exposta em 1874, deu nome ao movimento.',
    contextoHistorico: 'A França saía da guerra franco-prussiana e da Comuna de Paris; a reconstrução de Paris e o trem levavam os pintores a trabalhar ao ar livre.',
    contextoFilosofico: 'A fotografia já registrava o real; a pintura passou a explorar a percepção e a impressão momentânea.',
    contextoSocial: 'Os artistas foram recusados pelo Salão oficial e organizaram uma exposição independente, criticada como "impressão" inacabada.',
    curiosidade: 'O crítico Louis Leroy usou "impressionistas" como zombaria; o grupo adotou o nome.',
  },
  'girassois': {
    titulo: 'Os Girassóis', artista: 'Vincent van Gogh', ano: '1889', movimento: 'Pós-impressionismo', localAtual: 'Museu Van Gogh, Amsterdã (versão de 1889)',
    historia: 'Van Gogh pintou várias versões de girassóis em vaso para decorar o quarto do amigo Paul Gauguin em Arles. O amarelo era, para ele, a cor da amizade e da esperança.',
    contextoHistorico: 'O sul da França atraía artistas pela luz forte; Arles seria o sonho de um "ateliê do Sul" com Gauguin.',
    contextoFilosofico: 'A cor deixava de imitar a natureza para expressar sentimentos.',
    contextoSocial: 'A convivência com Gauguin terminou em briga e no episódio da orelha, em dezembro de 1888.',
    curiosidade: 'Os girassóis aparecem murchando e em flor no mesmo vaso: vida e fim juntos.',
  },
  'grande-onda': {
    titulo: 'A Grande Onda de Kanagawa', artista: 'Katsushika Hokusai', ano: 'c. 1831', movimento: 'Ukiyo-e (estampa japonesa)', localAtual: 'Várias impressões: Museu Metropolitano de Arte (Nova York), Museu Britânico (Londres) e outros',
    historia: 'Gravura em xilogravura da série "Trinta e Seis Vistas do Monte Fuji". A onda gigante ameaça barcos de pescadores enquanto o Fuji, pequeno, permanece imóvel ao fundo.',
    contextoHistorico: 'O Japão do período Edo vivia isolado do mundo (sakoku), com paz interna e uma economia de mercadores e cidades.',
    contextoFilosofico: 'Influência do budismo e do xintoísmo: a natureza é poderosa e o ser humano, passageiro.',
    contextoSocial: 'A xilogravura era arte popular e barata, comprada por comerciantes e artesãos das cidades.',
    curiosidade: 'A estampa chegou à Europa no século XIX e inspirou Monet, Van Gogh e Debussy (que a viu na capa de "La Mer").',
  },
  'nascimento-venus': {
    titulo: 'O Nascimento de Vênus', artista: 'Sandro Botticelli', ano: 'c. 1485', movimento: 'Renascimento italiano', localAtual: 'Galeria Uffizi, Florença',
    historia: 'Vênus chega à praia sobre uma concha, empurrada pelos ventos, enquanto uma Hora vem cobri-la com um manto. É um dos primeiros grandes nus mitológicos desde a Antiguidade.',
    contextoHistorico: 'Florença dos Médici, cidade de banqueiros e mecenas, era o centro do Renascimento.',
    contextoFilosofico: 'O neoplatonismo florentino via a beleza física como caminho para a beleza espiritual e divina.',
    contextoSocial: 'A obra foi feita para uma família poderosa ligada aos Médici, numa sociedade que unia fé cristã e cultura clássica.',
    curiosidade: 'É pintada em têmpera sobre tela, algo raro para a época, quando se preferia a madeira.',
  },
  'o-beijo': {
    titulo: 'O Beijo', artista: 'Gustav Klimt', ano: '1908', movimento: 'Art Nouveau / Secessão Vienense', localAtual: 'Belvedere, Viena',
    historia: 'Um casal abraçado sobre um prado florido, envolto por tecidos de ouro em folha. O dourado lembra os mosaicos bizantinos que Klimt viu em Ravena.',
    contextoHistorico: 'Viena do fim do Império Austro-Húngaro fervilhava de arte, música e ciência pouco antes da Primeira Guerra.',
    contextoFilosofico: 'Freud publicava sobre o inconsciente; o desejo e o simbolismo passaram a ser temas da arte.',
    contextoSocial: 'Klimt liderou a Secessão, que rompeu com o conservadorismo das academias.',
    curiosidade: 'A obra foi comprada pelo governo austríaco antes mesmo de ficar pronta.',
  },
  'autorretrato-rembrandt': {
    titulo: 'Autorretrato', artista: 'Rembrandt van Rijn', ano: '1659', movimento: 'Barroco holandês', localAtual: 'National Gallery of Art, Washington',
    historia: 'Um dos quase cem autorretratos do pintor, feito aos 53 anos. O rosto marcado pela idade e pela falência, iluminado com franqueza, mostra um homem que já viu a glória e a queda.',
    contextoHistorico: 'A Holanda vivia o auge do comércio, mas Rembrandt, arruinado por dívidas, perdeu a casa e a coleção em 1656.',
    contextoFilosofico: 'A arte holandesa valorizava a introspecção e a observação honesta da vida comum.',
    contextoSocial: 'Sem mecenas nobres, os artistas dependiam do mercado: quem saía de moda enfrentava a ruína.',
    curiosidade: 'Rembrandt se retratou ao longo de toda a vida, formando uma "autobiografia" em imagens.',
  },
  'leiteira': {
    titulo: 'A Leiteira', artista: 'Johannes Vermeer', ano: 'c. 1658', movimento: 'Barroco holandês', localAtual: 'Rijksmuseum, Amsterdã',
    historia: 'Uma criada derrama leite com concentração serena. Vermeer dá dignidade a um gesto cotidiano, com a luz da janela desenhando a cena.',
    contextoHistorico: 'A República Holandesa, próspera e protestante, valorizava o trabalho e a vida doméstica.',
    contextoFilosofico: 'A ética protestante enxergava virtude no ofício diário e na temperança.',
    contextoSocial: 'A criada, figura comum, torna-se protagonista, algo raro quando a arte servia à Igreja e à nobreza.',
    curiosidade: 'Pontinhos de luz sobre o pão foram feitos com pinceladas que lembram gotas brilhantes.',
  },
  'domingo-grande-jatte': {
    titulo: 'Um Domingo na Grande Jatte', artista: 'Georges Seurat', ano: '1886', movimento: 'Pontilhismo / Neoimpressionismo', localAtual: 'Art Institute of Chicago',
    historia: 'Parisienses passeiam num parque às margens do Sena em um domingo. Seurat levou dois anos compondo a tela com milhares de pequenos pontos de cor pura que se misturam no olhar.',
    contextoHistorico: 'A Paris industrial crescia; o domingo de lazer nasceu com o novo tempo livre da classe trabalhadora e da burguesia.',
    contextoFilosofico: 'A fé na ciência levou o pintor a aplicar teorias ópticas sobre cor e percepção.',
    contextoSocial: 'A tela mostra várias classes sociais no mesmo espaço, mas sem interagir, o que já é um comentário sobre a cidade moderna.',
    curiosidade: 'Ela inspirou o musical "Sunday in the Park with George", de Stephen Sondheim.',
  },
  'mona-lisa': {
    titulo: 'Mona Lisa', artista: 'Leonardo da Vinci', ano: 'c. 1503', movimento: 'Alto Renascimento', localAtual: 'Museu do Louvre, Paris',
    historia: 'Retrato de Lisa Gherardini, esposa de um mercador florentino. Leonardo usou o sfumato, transições suaves sem contornos duros, e nunca entregou a obra: levou-a consigo até a França, onde morreu.',
    contextoHistorico: 'A Itália renascentista redescobria a Antiguidade; Florença, Milão e Roma disputavam artistas e sábios.',
    contextoFilosofico: 'O humanismo colocava o ser humano e sua razão no centro do mundo, e a observação da natureza virava método.',
    contextoSocial: 'Artistas eram vistos como gênios e cientistas: Leonardo estudava anatomia, óptica e engenharia.',
    curiosidade: 'A obra foi roubada em 1911 e voltou ao Louvre em 1914, o que a tornou ainda mais famosa.',
  },
  'venus-de-milo': {
    titulo: 'Vênus de Milo', artista: 'Alexandros de Antioquia (atribuição)', ano: 'c. 100 a.C.', movimento: 'Escultura helenística', localAtual: 'Museu do Louvre, Paris',
    historia: 'Estátua de mármore encontrada em 1820 na ilha grega de Milos, provavelmente representando Afrodite. Os braços nunca foram achados, e isso alimenta séculos de hipóteses.',
    contextoHistorico: 'O mundo helenístico sucedia o império de Alexandre, espalhando a cultura grega do Mediterrâneo ao Oriente.',
    contextoFilosofico: 'O ideal grego de harmonia e proporção buscava a beleza como expressão da ordem do universo.',
    contextoSocial: 'A França do século XIX disputava com outras potências peças da Antiguidade para engrandecer seus museus.',
    curiosidade: 'A escultura tem cerca de 2 metros, e a pose em espiral (contrapposto) lhe dá movimento.',
  },
  'las-meninas': {
    titulo: 'As Meninas', artista: 'Diego Velázquez', ano: '1656', movimento: 'Barroco espanhol', localAtual: 'Museu do Prado, Madri',
    historia: 'A infanta Margarida e suas damas no ateliê do pintor, que se retrata pintando. Um espelho ao fundo mostra os reis, e o espectador ocupa o lugar de quem é observado.',
    contextoHistorico: 'A Espanha do Século de Ouro, ainda rica em arte, já declinava politicamente sob Filipe IV.',
    contextoFilosofico: 'O Barroco brincava com ilusão e realidade, e a obra questiona quem olha e quem é olhado.',
    contextoSocial: 'Velázquez foi pintor da corte e lutou para ser reconhecido como nobre, algo negado a quem "trabalhava com as mãos".',
    curiosidade: 'Picasso pintou mais de 40 releituras da obra.',
  },
  'ronda-da-noite': {
    titulo: 'A Ronda Noturna', artista: 'Rembrandt van Rijn', ano: '1642', movimento: 'Barroco holandês', localAtual: 'Rijksmuseum, Amsterdã',
    historia: 'Retrato coletivo de uma companhia de milícia cívica de Amsterdã em movimento. O contraste de luz e sombra cria drama, e cada figura parece prestes a agir.',
    contextoHistorico: 'A Holanda, recém-independente da Espanha, mantinha milícias cívicas para defender as cidades.',
    contextoFilosofico: 'O Barroco valorizava o dinamismo e o instante, em oposição à serenidade renascentista.',
    contextoSocial: 'Os membros pagavam pelo retrato; alguns se queixaram por ficarem na sombra.',
    curiosidade: 'Não é uma cena noturna: o verniz escurecido pelo tempo criou o nome "Ronda Noturna".',
  },
  'o-grito': {
    titulo: 'O Grito', artista: 'Edvard Munch', ano: '1893', movimento: 'Expressionismo / Simbolismo', localAtual: 'Galeria Nacional, Oslo (versão de 1893)',
    historia: 'Uma figura leva as mãos ao rosto sob um céu vermelho, numa ponte em Oslo. Munch contou ter sentido "um grito infinito atravessando a natureza" durante um passeio ao entardecer.',
    contextoHistorico: 'A Europa do fim do século XIX vivia acelerada pela industrialização e pela urbanização.',
    contextoFilosofico: 'Kierkegaard e Nietzsche falavam de angústia e do vazio moderno; a psicologia nascia.',
    contextoSocial: 'Munch, marcado por mortes na família e por uma saúde frágil, transformou o sofrimento pessoal em símbolo coletivo.',
    curiosidade: 'Munch fez mais de uma versão do tema, e a de pastel foi vendida em 2012 por quase 120 milhões de dólares.',
  },
  'viajante-nevoeiro': {
    titulo: 'O Viajante sobre o Mar de Névoa', artista: 'Caspar David Friedrich', ano: 'c. 1818', movimento: 'Romantismo alemão', localAtual: 'Kunsthalle, Hamburgo',
    historia: 'Um homem, de costas, contempla montanhas cobertas de névoa. O espectador vê com ele: diante do sublime, cada um se sente pequeno e livre.',
    contextoHistorico: 'A Europa saía das guerras napoleônicas; os estados alemães buscavam identidade.',
    contextoFilosofico: 'O Romantismo e o conceito de sublime de Kant e Burke: a natureza inspira ao mesmo tempo medo e êxtase.',
    contextoSocial: 'Reação ao racionalismo iluminista, valorizando a emoção, a solidão e o indivíduo.',
    curiosidade: 'A figura de costas, a "Rückenfigur", virou marca do pintor.',
  },
  'ninfeias': {
    titulo: 'Ninfeias', artista: 'Claude Monet', ano: '1906', movimento: 'Impressionismo tardio', localAtual: 'Art Institute of Chicago (esta versão)',
    historia: 'Monet construiu o jardim aquático de Giverny e o pintou por três décadas, mais de duzentas vezes. Sem horizonte, a tela vira superfície de reflexos.',
    contextoHistorico: 'A Europa entrava no século XX, da eletricidade, do automóvel e das vanguardas.',
    contextoFilosofico: 'Bergson falava do tempo vivido, e a pintura tentava captar a duração e a mudança da luz.',
    contextoSocial: 'Monet, já célebre e próspero, podia pintar apenas para si, em seu próprio jardim.',
    curiosidade: 'Quase cego pela catarata, ele seguiu pintando; as versões tardias são quase abstratas.',
  },
  'jardim-das-delicias': {
    titulo: 'O Jardim das Delícias Terrenas', artista: 'Hieronymus Bosch', ano: 'c. 1500', movimento: 'Renascimento nórdico', localAtual: 'Museu do Prado, Madri',
    historia: 'Tríptico com o Paraíso, um jardim de prazeres e o Inferno. Criaturas fantásticas e cenas enigmáticas povoam os painéis, e até hoje se discute o sentido da obra.',
    contextoHistorico: 'A Europa entre o fim da Idade Média e as grandes navegações vivia medos apocalípticos e curiosidades sobre o mundo.',
    contextoFilosofico: 'Moralismo cristão sobre pecado e salvação convivia com o nascimento do humanismo.',
    contextoSocial: 'Bosch, de família de artistas em \'s-Hertogenbosch, pintava para uma elite culta e religiosa.',
    curiosidade: 'Os painéis fechados mostram a Terra no terceiro dia da Criação, em tons de cinza.',
  },
  'casal-arnolfini': {
    titulo: 'O Casal Arnolfini', artista: 'Jan van Eyck', ano: '1434', movimento: 'Renascimento nórdico (primitivos flamengos)', localAtual: 'National Gallery, Londres',
    historia: 'Retrato de um mercador italiano e sua esposa em Bruges. Um espelho convexo ao fundo reflete a cena e duas figuras, incluindo, talvez, o próprio pintor, com a assinatura "Jan van Eyck esteve aqui".',
    contextoHistorico: 'Bruges era um grande centro de comércio e finanças, e o ducado da Borgonha, uma potência cultural.',
    contextoFilosofico: 'O simbolismo cristão se escondia em objetos comuns: a vela única, o cão, as frutas.',
    contextoSocial: 'A nova burguesia comerciante passava a encomendar retratos, antes privilégio da nobreza e da Igreja.',
    curiosidade: 'Van Eyck aperfeiçoou a pintura a óleo, com camadas finas e transparentes.',
  },
  'ultima-ceia': {
    titulo: 'A Última Ceia', artista: 'Leonardo da Vinci', ano: 'c. 1498', movimento: 'Alto Renascimento', localAtual: 'Convento de Santa Maria delle Grazie, Milão',
    historia: 'Mural que retrata o momento em que Jesus anuncia que será traído. Cada apóstolo reage de um jeito, e a perspectiva conduz o olhar ao centro da cena.',
    contextoHistorico: 'Milão de Ludovico Sforza, protetor de Leonardo, era uma das cortes mais brilhantes da Itália.',
    contextoFilosofico: 'O Renascimento unia fé e ciência: a geometria da perspectiva organiza o drama espiritual.',
    contextoSocial: 'A obra foi encomendada para o refeitório dos frades, para ser vista enquanto eles comiam.',
    curiosidade: 'Leonardo testou uma técnica nova em parede seca, e por isso a pintura começou a se deteriorar em poucas décadas.',
  },
  'carroca-de-feno': {
    titulo: 'A Carroça de Feno', artista: 'John Constable', ano: '1821', movimento: 'Romantismo inglês', localAtual: 'National Gallery, Londres',
    historia: 'Uma carroça atravessa o rio Stour, diante da casa de Willy Lott, na paisagem onde Constable cresceu. Ele pintou nuvens e luz com estudos feitos ao ar livre.',
    contextoHistorico: 'A Inglaterra vivia a Revolução Industrial: cidades e fábricas cresciam, e o campo virava lembrança.',
    contextoFilosofico: 'O Romantismo buscava na natureza o consolo e a verdade emocional.',
    contextoSocial: 'A obra foi mais celebrada na França do que na Inglaterra, e influenciou a escola de Barbizon.',
    curiosidade: 'Na França, ganhou medalha no Salão de Paris de 1824, e Delacroix repintou partes de sua própria tela depois de vê-la.',
  },
  'liberdade-guiando-povo': {
    titulo: 'A Liberdade Guiando o Povo', artista: 'Eugène Delacroix', ano: '1830', movimento: 'Romantismo francês', localAtual: 'Museu do Louvre, Paris',
    historia: 'Uma mulher com a bandeira tricolor lidera revolucionários sobre corpos de caídos. A cena homenageia as "Três Gloriosas", a revolta de julho de 1830 em Paris.',
    contextoHistorico: 'A Revolução de Julho derrubou Carlos X e levou Luís Filipe ao trono.',
    contextoFilosofico: 'O ideal de liberdade do Iluminismo e da Revolução Francesa ainda mobilizava a Europa.',
    contextoSocial: 'Operários, estudantes e burgueses lutam juntos: a figura do menino com pistolas lembra a juventude das barricadas.',
    curiosidade: 'O governo comprou a tela, mas a escondeu por anos por considerá-la subversiva.',
  },
  'almoco-remadores': {
    titulo: 'O Almoço dos Remadores', artista: 'Pierre-Auguste Renoir', ano: '1881', movimento: 'Impressionismo', localAtual: 'Coleção Phillips, Washington',
    historia: 'Amigos do pintor almoçam numa varanda às margens do Sena, em Chatou. A cena transborda conversa, luz filtrada e alegria de viver.',
    contextoHistorico: 'A Terceira República francesa trouxe estabilidade e a Belle Époque, com trens levando parisienses ao campo aos domingos.',
    contextoFilosofico: 'O prazer do cotidiano e da convivência virou tema legítimo da arte.',
    contextoSocial: 'Uma sociedade urbana com tempo livre e dinheiro para o lazer aparece como protagonista.',
    curiosidade: 'Muitos dos personagens eram amigos reais de Renoir, e a futura esposa dele aparece na cena.',
  },
  'bar-folies-bergere': {
    titulo: 'Um Bar no Folies-Bergère', artista: 'Édouard Manet', ano: '1882', movimento: 'Realismo / Impressionismo', localAtual: 'Instituto Courtauld, Londres',
    historia: 'Uma garçonete encara o espectador diante de um espelho que reflete a multidão do cabaré. O reflexo não bate com a perspectiva, e a distância emocional dela é o assunto do quadro.',
    contextoHistorico: 'A Paris dos cabarés e cafés-concerto era o palco da vida moderna.',
    contextoFilosofico: 'O olhar moderno mostra alienação e anonimato em meio à multidão.',
    contextoSocial: 'A mulher que trabalha, exposta ao público e a olhares masculinos, era um retrato social do trabalho feminino.',
    curiosidade: 'Foi a última grande tela de Manet, pintada quando já estava doente.',
  },
  'olimpia': {
    titulo: 'Olympia', artista: 'Édouard Manet', ano: '1863', movimento: 'Realismo', localAtual: 'Museu d\'Orsay, Paris',
    historia: 'Uma mulher nua, uma cortesã, encara o espectador com olhar direto, ao lado de uma criada que traz flores. Manet reinterpretou a Vênus de Ticiano com a modernidade parisiense.',
    contextoHistorico: 'O Segundo Império de Napoleão III reformava Paris e alimentava uma cultura de luxo e prazer.',
    contextoFilosofico: 'O Realismo pedia que a arte mostrasse a vida contemporânea, sem véu mitológico.',
    contextoSocial: 'O escândalo no Salão de 1865 veio menos da nudez que da franqueza: a modelo era reconhecível como mulher real e seu ofício, evidente.',
    curiosidade: 'A criada negra, Laure, foi retratada com dignidade e hoje é tema de muitos estudos.',
  },
  'terraco-cafe-noite': {
    titulo: 'Terraço de Café à Noite', artista: 'Vincent van Gogh', ano: '1888', movimento: 'Pós-impressionismo', localAtual: 'Museu Kröller-Müller, Otterlo',
    historia: 'Um café de Arles iluminado por lampiões amarelos sob um céu estrelado. Foi a primeira vez que Van Gogh pintou uma cena noturna direto ao ar livre, sem usar preto.',
    contextoHistorico: 'A luz elétrica e a vida noturna se espalhavam pelas cidades europeias.',
    contextoFilosofico: 'A cor deixava de descrever e passava a exprimir a sensação.',
    contextoSocial: 'O café era o espaço público de encontro, um dos lugares em que o pintor buscava companhia.',
    curiosidade: 'Uma leitura popular vê, nos apóstolos e na cruz da janela, um eco da Última Ceia, embora Van Gogh não o tenha afirmado.',
  },
  'quarto-arles': {
    titulo: 'O Quarto em Arles', artista: 'Vincent van Gogh', ano: '1888', movimento: 'Pós-impressionismo', localAtual: 'Museu Van Gogh, Amsterdã (versão de 1888)',
    historia: 'O quarto simples da Casa Amarela, pintado com cores chapadas e perspectiva propositalmente estranha. Van Gogh queria transmitir repouso e descanso.',
    contextoHistorico: 'A gravura japonesa, popular em Paris, inspirou o uso de cores planas e contornos.',
    contextoFilosofico: 'O sentimento do artista importa mais que a exatidão da perspectiva.',
    contextoSocial: 'O pintor vivia com poucos recursos, e o quarto reflete sua busca por um lar.',
    curiosidade: 'Ele pintou três versões: a segunda foi feita depois de uma internação.',
  },
  'madame-x': {
    titulo: 'Madame X', artista: 'John Singer Sargent', ano: '1884', movimento: 'Realismo / Retrato mundano', localAtual: 'Museu Metropolitano de Arte, Nova York',
    historia: 'Retrato de Virginie Gautreau, socialite parisiense conhecida pela pele muito clara. A alça do vestido, originalmente caída no ombro, causou escândalo e foi repintada pelo artista.',
    contextoHistorico: 'A Paris da Belle Époque cultuava a moda, a aparência e a reputação.',
    contextoFilosofico: 'Tensão entre a exibição de si e a moral burguesa.',
    contextoSocial: 'A alta sociedade usava retratos como instrumento de prestígio, e o escândalo custou a Sargent a carreira em Paris, levando-o a Londres.',
    curiosidade: 'Sargent vendeu a tela ao Met em 1916 e disse que era "a melhor coisa que já fiz".',
  },
  'primavera': {
    titulo: 'A Primavera', artista: 'Sandro Botticelli', ano: 'c. 1480', movimento: 'Renascimento italiano', localAtual: 'Galeria Uffizi, Florença',
    historia: 'Vênus preside um jardim onde as Três Graças dançam, Mercúrio afasta as nuvens e Flora espalha flores. Centenas de plantas foram identificadas na pintura.',
    contextoHistorico: 'Florença dos Médici vivia seu apogeu artístico e político.',
    contextoFilosofico: 'O neoplatonismo de Marsílio Ficino unia mitologia clássica e espiritualidade cristã.',
    contextoSocial: 'Provavelmente encomendada para uma casa de família ligada aos Médici, possivelmente por ocasião de casamento.',
    curiosidade: 'O título "Primavera" foi dado depois, por Giorgio Vasari, no século XVI.',
  },
  'escola-de-atenas': {
    titulo: 'A Escola de Atenas', artista: 'Rafael Sanzio', ano: '1511', movimento: 'Alto Renascimento', localAtual: 'Palácio Apostólico, Vaticano (Sala da Assinatura)',
    historia: 'Afresco que reúne os grandes filósofos da Antiguidade sob uma arquitetura monumental. No centro, Platão aponta para o céu e Aristóteles, para a terra.',
    contextoHistorico: 'O papa Júlio II fez de Roma o centro cultural, contratando Rafael e Michelangelo ao mesmo tempo.',
    contextoFilosofico: 'O humanismo tentava conciliar o saber pagão da Grécia com o pensamento cristão.',
    contextoSocial: 'A Igreja era o grande mecenas, mas o programa celebrava a razão e o conhecimento.',
    curiosidade: 'Rafael deu ao rosto de Platão as feições de Leonardo, e ao de Heráclito, as de Michelangelo.',
  },
  'criacao-de-adao': {
    titulo: 'O Teto da Capela Sistina', artista: 'Michelangelo', ano: '1508–1512', movimento: 'Alto Renascimento', localAtual: 'Capela Sistina, Vaticano',
    historia: 'Michelangelo pintou quase 500 m² de teto em afrescos com cenas do Gênesis. A cena mais famosa, "A Criação de Adão", mostra o quase-toque entre o dedo de Deus e o do homem.',
    contextoHistorico: 'O papa Júlio II queria glorificar o papado, e Michelangelo se considerava escultor, aceitando a tarefa a contragosto.',
    contextoFilosofico: 'O corpo humano, exaltado, era visto como imagem do divino.',
    contextoSocial: 'A obra levou quatro anos, com o artista trabalhando em andaimes e com dores no pescoço e nas costas.',
    curiosidade: 'Uma teoria diz que o manto de Deus lembraria a forma de um cérebro humano, mas é uma interpretação, não um fato comprovado.',
  },
  'arte-da-pintura': {
    titulo: 'A Arte da Pintura', artista: 'Johannes Vermeer', ano: 'c. 1668', movimento: 'Barroco holandês', localAtual: 'Museu de História da Arte, Viena',
    historia: 'Um pintor de costas trabalha diante de uma modelo coroada de louros, que representa Clio, a musa da História. Vermeer reflete sobre o próprio ofício e sua dignidade.',
    contextoHistorico: 'Os Países Baixos viviam a guerra contra a França, e o mercado de arte entrava em crise.',
    contextoFilosofico: 'Alegoria do valor da pintura como conhecimento e como memória.',
    contextoSocial: 'Vermeer guardou a obra consigo até morrer, e sua viúva teve de vendê-la para pagar dívidas.',
    curiosidade: 'Hitler a comprou em 1940, e ela foi recuperada depois da guerra.',
  },
  'judite-klimt': {
    titulo: 'Judite e a Cabeça de Holofernes', artista: 'Gustav Klimt', ano: '1901', movimento: 'Simbolismo / Secessão Vienense', localAtual: 'Belvedere, Viena',
    historia: 'Klimt retrata Judite, a heroína bíblica que salvou seu povo decapitando um general inimigo, como uma mulher sensual e segura, em ouro. A cabeça de Holofernes aparece cortada na borda da tela.',
    contextoHistorico: 'A Viena de 1900 vivia o auge da Secessão e do Simbolismo.',
    contextoFilosofico: 'Freud, Schnitzler e o simbolismo exploravam o desejo, o poder e a ameaça feminina.',
    contextoSocial: 'Mulheres começavam a reivindicar novos papéis, e artistas as viam com fascínio e temor.',
    curiosidade: 'Por muito tempo a obra foi confundida com Salomé, outra figura bíblica.',
  },
  'adele-bloch-bauer': {
    titulo: 'Retrato de Adele Bloch-Bauer I', artista: 'Gustav Klimt', ano: '1907', movimento: 'Art Nouveau / Período Dourado', localAtual: 'Neue Galerie, Nova York',
    historia: 'Retrato de uma mecenas da alta sociedade vienense, envolvida em folha de ouro e padrões geométricos. É o ápice do "período dourado" de Klimt.',
    contextoHistorico: 'A Viena imperial via florescer uma burguesia judaica culta e rica, mecenas das artes.',
    contextoFilosofico: 'A arte total: pintura, ornamento e arquitetura formam um só ambiente.',
    contextoSocial: 'Os nazistas confiscaram a obra em 1938; a sobrinha de Adele lutou anos na justiça e a recuperou em 2006.',
    curiosidade: 'Foi vendida em 2006 por 135 milhões de dólares, um recorde para a época.',
  },
  'caipira-picando-fumo': {
    titulo: 'Caipira Picando Fumo', artista: 'Almeida Júnior', ano: '1893', movimento: 'Realismo brasileiro', localAtual: 'Pinacoteca do Estado de São Paulo',
    historia: 'Um homem do interior paulista prepara o fumo de corda em pose descontraída, sem idealização. Almeida Júnior retratou o povo simples numa época em que a pintura acadêmica buscava temas históricos.',
    contextoHistorico: 'A abolição da escravatura (1888) e a Proclamação da República (1889) transformaram o Brasil.',
    contextoFilosofico: 'O Realismo e o positivismo valorizavam a observação da vida como ela é.',
    contextoSocial: 'A obra dá dignidade ao homem do campo e à cultura rural paulista.',
    curiosidade: 'Almeida Júnior foi um dos primeiros grandes pintores brasileiros a se afastar do academicismo do Rio de Janeiro.',
  },
  'independencia-ou-morte': {
    titulo: 'Independência ou Morte', artista: 'Pedro Américo', ano: '1888', movimento: 'Academicismo / Pintura histórica', localAtual: 'Museu do Ipiranga, São Paulo',
    historia: 'Cena idealizada do "Grito do Ipiranga", em 7 de setembro de 1822, com Dom Pedro I às margens do riacho. Foi pintada mais de 60 anos depois, em Florença.',
    contextoHistorico: 'O Império do Brasil vivia seus últimos anos, e a monarquia buscava reforçar sua origem heroica.',
    contextoFilosofico: 'O nacionalismo do século XIX construía mitos de origem para as jovens nações.',
    contextoSocial: 'A imagem moldou a memória coletiva, embora historiadores apontem que os detalhes (uniformes, cavalos) foram embelezados.',
    curiosidade: 'Uma frase clássica atribui a Dom Pedro o grito, mas não há registro exato de suas palavras.',
  },
  'primeira-missa': {
    titulo: 'A Primeira Missa no Brasil', artista: 'Victor Meirelles', ano: '1861', movimento: 'Academicismo romântico', localAtual: 'Museu Nacional de Belas Artes, Rio de Janeiro',
    historia: 'Encenação da missa celebrada em abril de 1500 pelos portugueses, com indígenas observando. Inspirada na carta de Pero Vaz de Caminha, é uma imagem fundadora da história oficial do Brasil.',
    contextoHistorico: 'O Segundo Reinado de Dom Pedro II buscava criar uma identidade nacional e apoiava a arte.',
    contextoFilosofico: 'O Romantismo brasileiro idealizava o indígena e o encontro entre povos.',
    contextoSocial: 'A visão é a do colonizador; hoje é lida também como símbolo do apagamento dos povos originários.',
    curiosidade: 'Meirelles estudou em Roma e em Paris, com bolsa do Império, antes de pintar a obra.',
  },
  'fuji-vermelho': {
    titulo: 'Vento Sul, Céu Claro (Fuji Vermelho)', artista: 'Katsushika Hokusai', ano: 'c. 1831', movimento: 'Ukiyo-e (estampa japonesa)', localAtual: 'Várias impressões em museus do mundo',
    historia: 'O Monte Fuji, avermelhado pela luz do amanhecer em certos dias de fim de verão, domina o céu. Faz parte da mesma série da "Grande Onda".',
    contextoHistorico: 'No Japão Edo, o Fuji era símbolo sagrado e destino de peregrinação.',
    contextoFilosofico: 'A relação entre humano e natureza, típica do xintoísmo, dá à montanha um sentido espiritual.',
    contextoSocial: 'A prosperidade dos mercadores criou público para paisagens e viagens em estampas.',
    curiosidade: 'Hokusai tinha cerca de 70 anos quando fez a série e dizia que só aos 110 seria um verdadeiro mestre.',
  },
  'chuva-ponte-ohashi': {
    titulo: 'Chuva Repentina sobre a Ponte Shin-Ohashi', artista: 'Utagawa Hiroshige', ano: '1857', movimento: 'Ukiyo-e (estampa japonesa)', localAtual: 'Museu Brooklyn, Nova York (e outras coleções)',
    historia: 'Pessoas correm sob uma chuva forte na ponte sobre o rio Sumida, em Edo (atual Tóquio). As linhas diagonais da chuva dão sensação de movimento.',
    contextoHistorico: 'Edo era uma das maiores cidades do mundo, e o Japão ainda estava fechado ao Ocidente até 1853.',
    contextoFilosofico: 'A estética japonesa valoriza o efêmero (mono no aware).',
    contextoSocial: 'A obra faz parte de "Cem Vistas Famosas de Edo", que servia de souvenir para moradores e viajantes.',
    curiosidade: 'Van Gogh copiou essa estampa a óleo em 1887.',
  },
  'temerario': {
    titulo: 'O Último Trajeto do Temerário', artista: 'J. M. W. Turner', ano: '1839', movimento: 'Romantismo', localAtual: 'National Gallery, Londres',
    historia: 'Um veleiro de guerra glorioso, herói de Trafalgar, é rebocado por um pequeno vapor para ser desmontado, sob um pôr do sol dourado. Turner faz da cena uma elegia da era da vela.',
    contextoHistorico: 'A Grã-Bretanha era a potência industrial e naval do mundo, e o vapor substituía a vela.',
    contextoFilosofico: 'O Romantismo enxergava melancolia no fim de uma era e no avanço do progresso.',
    contextoSocial: 'O público londrino via na obra a despedida de uma memória nacional.',
    curiosidade: 'Uma pesquisa popular de 2005 elegeu a tela a maior pintura britânica de todos os tempos.',
  },
  'judite-caravaggio': {
    titulo: 'Judite Decapitando Holofernes', artista: 'Caravaggio', ano: 'c. 1599', movimento: 'Barroco italiano', localAtual: 'Galeria Nacional de Arte Antiga (Palazzo Barberini), Roma',
    historia: 'A heroína bíblica decapita o general assírio com esforço e repulsa, enquanto a criada aguarda. A luz teatral, o "tenebrismo", intensifica o drama.',
    contextoHistorico: 'A Contrarreforma católica queria uma arte que emocionasse os fiéis e reafirmasse a fé.',
    contextoFilosofico: 'O Barroco explorava o conflito, o realismo e a tensão do instante.',
    contextoSocial: 'Caravaggio usava pessoas comuns como modelos, algo escandaloso para os padrões de idealização.',
    curiosidade: 'O pintor levou vida turbulenta, foi condenado por homicídio e fugiu de Roma.',
  },
  'tres-de-maio': {
    titulo: 'Os Fuzilamentos de 3 de Maio', artista: 'Francisco de Goya', ano: '1814', movimento: 'Romantismo espanhol', localAtual: 'Museu do Prado, Madri',
    historia: 'Civis espanhóis são executados por soldados franceses depois do levante de Madri contra Napoleão, em maio de 1808. O homem de camisa branca abre os braços em desafio.',
    contextoHistorico: 'A Guerra Peninsular (1808–1814) opôs a Espanha à ocupação napoleônica.',
    contextoFilosofico: 'Goya, marcado pelo Iluminismo, mostrou a violência sem heroísmo, condenando a guerra em si.',
    contextoSocial: 'Ao retratar vítimas anônimas, e não generais, a obra muda o foco da história para o povo.',
    curiosidade: 'É considerada uma das primeiras grandes pinturas de protesto contra a guerra; inspirou Manet e Picasso ("Guernica").',
  },
  'menino-azul': {
    titulo: 'O Menino Azul', artista: 'Thomas Gainsborough', ano: 'c. 1770', movimento: 'Retrato inglês do século XVIII', localAtual: 'Biblioteca Huntington, San Marino (Califórnia)',
    historia: 'Um jovem em traje de seda azul, ao estilo do século XVII, posa com elegância. Diz-se que Gainsborough quis contrariar a regra de Reynolds de que o azul não deveria dominar um quadro.',
    contextoHistorico: 'A Inglaterra do século XVIII era rica em comércio e império, e a aristocracia encomendava retratos para afirmar status.',
    contextoFilosofico: 'O Iluminismo inglês valorizava a razão e a polidez, mas o retrato ainda buscava idealizar.',
    contextoSocial: 'Retratos como este consolidavam a imagem da elite rural e mercantil.',
    curiosidade: 'Em 1922 a tela foi vendida aos Estados Unidos, e milhares de pessoas foram se despedir dela em Londres.',
  },
  'grande-odalisca': {
    titulo: 'A Grande Odalisca', artista: 'Jean-Auguste-Dominique Ingres', ano: '1814', movimento: 'Neoclassicismo', localAtual: 'Museu do Louvre, Paris',
    historia: 'Uma odalisca, mulher de harém, reclina-se com um corpo de proporções alongadas de propósito, com vértebras a mais. Ingres priorizava a linha elegante sobre a exatidão anatômica.',
    contextoHistorico: 'A França de Napoleão fascinava-se com o Oriente após as campanhas no Egito.',
    contextoFilosofico: 'O Neoclassicismo defendia a linha e a razão; o Romantismo defendia a cor e a emoção.',
    contextoSocial: 'O orientalismo criava uma visão idealizada e estereotipada do Oriente para o público europeu.',
    curiosidade: 'Críticos da época apontaram as proporções "erradas", mas Ingres afirmava que a beleza justificava a liberdade.',
  },
  'mae-de-whistler': {
    titulo: 'Arranjo em Cinza e Preto (A Mãe de Whistler)', artista: 'James McNeill Whistler', ano: '1871', movimento: 'Esteticismo / Tonalismo', localAtual: 'Museu d\'Orsay, Paris',
    historia: 'A mãe do pintor, de perfil, sentada com serenidade diante de uma parede quase vazia. Whistler queria destacar harmonia de formas e tons, mais do que contar uma história.',
    contextoHistorico: 'A era vitoriana valorizava a família e a respeitabilidade.',
    contextoFilosofico: '"A arte pela arte": a beleza vale por si, sem precisar de moral ou narrativa.',
    contextoSocial: 'Whistler foi um artista americano em Londres e em Paris, que brigou com críticos como John Ruskin.',
    curiosidade: 'O título formal mostra que, para o artista, o tema era secundário: importava o arranjo de cores.',
  },
  'cigana-adormecida': {
    titulo: 'A Cigana Adormecida', artista: 'Henri Rousseau', ano: '1897', movimento: 'Arte naïf / Primitivismo', localAtual: 'MoMA, Nova York',
    historia: 'Uma mulher dorme no deserto ao luar, com um bandolim e uma jarra, enquanto um leão a cheira sem atacar. Rousseau chamou o quadro de sonho poético.',
    contextoHistorico: 'A Paris do fim do século XIX descobria a arte "ingênua" e as culturas de fora da Europa.',
    contextoFilosofico: 'O Simbolismo e o interesse pelo onírico antecipavam o Surrealismo.',
    contextoSocial: 'Rousseau, funcionário da alfândega e pintor autodidata, foi ridicularizado e depois admirado por Picasso e outros.',
    curiosidade: 'Ele ofereceu o quadro à prefeitura de sua cidade, que recusou.',
  },
  'baile-moulin': {
    titulo: 'Baile no Moulin de la Galette', artista: 'Pierre-Auguste Renoir', ano: '1876', movimento: 'Impressionismo', localAtual: 'Museu d\'Orsay, Paris',
    historia: 'Uma festa dominical ao ar livre em Montmartre, com luz filtrada pelas árvores em manchas sobre as roupas. Muitos amigos de Renoir posaram.',
    contextoHistorico: 'Depois da guerra de 1870, Paris renascia com bailes populares e cafés.',
    contextoFilosofico: 'O Impressionismo celebrava a alegria do momento e a experiência sensorial.',
    contextoSocial: 'Trabalhadores e artistas se misturavam num lazer acessível.',
    curiosidade: 'A tela foi vendida por 78 milhões de dólares em 1990, em um dos maiores leilões da época.',
  },
  'cacadores-na-neve': {
    titulo: 'Caçadores na Neve', artista: 'Pieter Bruegel, o Velho', ano: '1565', movimento: 'Renascimento flamengo', localAtual: 'Museu de História da Arte, Viena',
    historia: 'Caçadores voltam com pouca caça por uma paisagem de inverno, enquanto aldeões patinam ao fundo. Faz parte de uma série sobre as estações do ano.',
    contextoHistorico: 'O inverno de 1564–65 foi um dos mais frios da chamada Pequena Era do Gelo na Europa.',
    contextoFilosofico: 'A vida do campo era mostrada com humor e sabedoria popular, sem idealização.',
    contextoSocial: 'A obra pertencia a um rico mercador de Antuérpia, cidade próspera, mas sob tensão religiosa.',
    curiosidade: 'Ela aparece em filmes como "Solaris", de Tarkovski.',
  },
  'torre-de-babel': {
    titulo: 'A Torre de Babel', artista: 'Pieter Bruegel, o Velho', ano: '1563', movimento: 'Renascimento flamengo', localAtual: 'Museu de História da Arte, Viena (versão de 1563)',
    historia: 'A torre bíblica, erguida pelo orgulho humano, aparece enorme e já desabando, inspirada no Coliseu de Roma. Trabalhadores minúsculos revelam a escala da obra.',
    contextoHistorico: 'Antuérpia era um centro cosmopolita de comércio, onde se falavam muitas línguas.',
    contextoFilosofico: 'A parábola alerta contra a soberba e a ambição desmedida.',
    contextoSocial: 'A obra podia aludir aos conflitos religiosos e ao poder da Espanha sobre os Países Baixos.',
    curiosidade: 'Bruegel pintou pelo menos duas versões; a de Roterdã é menor.',
  },
  'embaixadores': {
    titulo: 'Os Embaixadores', artista: 'Hans Holbein, o Jovem', ano: '1533', movimento: 'Renascimento do Norte', localAtual: 'National Gallery, Londres',
    historia: 'Dois franceses cultos e ricos posam ao lado de instrumentos científicos e livros. No chão, uma forma distorcida só se revela como caveira quando vista de lado.',
    contextoHistorico: 'A Reforma dividia a Europa, e a Inglaterra de Henrique VIII rompia com Roma.',
    contextoFilosofico: 'O "memento mori" lembra que o poder e o conhecimento são passageiros.',
    contextoSocial: 'O retrato exibe status, erudição e diplomacia numa Europa em tensão religiosa.',
    curiosidade: 'O truque da caveira usa anamorfose, técnica de perspectiva deformada.',
  },
  'venus-de-urbino': {
    titulo: 'A Vênus de Urbino', artista: 'Ticiano', ano: '1538', movimento: 'Renascimento veneziano', localAtual: 'Galeria Uffizi, Florença',
    historia: 'Uma mulher nua reclina-se num quarto com um cão adormecido, enquanto criadas procuram roupas num baú. Encomendada pelo duque de Urbino, a obra funde mitologia e vida doméstica.',
    contextoHistorico: 'Veneza, república comercial, rivalizava com Florença e Roma como centro da arte.',
    contextoFilosofico: 'A cor e a sensualidade venezianas contrastavam com o desenho florentino.',
    contextoSocial: 'A pintura talvez celebrasse a fidelidade conjugal, simbolizada pelo cão e pelo mirto.',
    curiosidade: 'Inspirou "Olympia", de Manet, três séculos depois.',
  },
  'jangada-da-medusa': {
    titulo: 'A Jangada da Medusa', artista: 'Théodore Géricault', ano: '1819', movimento: 'Romantismo francês', localAtual: 'Museu do Louvre, Paris',
    historia: 'Sobreviventes de um naufrágio de 1816 lutam à deriva numa jangada e avistam um navio distante. Géricault entrevistou os sobreviventes e estudou cadáveres para pintar a cena.',
    contextoHistorico: 'O naufrágio da fragata Méduse ocorreu no retorno da monarquia Bourbon, e o capitão incompetente era ligado à corte.',
    contextoFilosofico: 'O Romantismo expõe o sofrimento e a esperança extrema do ser humano.',
    contextoSocial: 'A tragédia virou escândalo político e crítica ao governo.',
    curiosidade: 'A tela mede mais de 7 metros de largura, com figuras em tamanho natural.',
  },
  'respigadoras': {
    titulo: 'As Respigadoras', artista: 'Jean-François Millet', ano: '1857', movimento: 'Realismo (Escola de Barbizon)', localAtual: 'Museu d\'Orsay, Paris',
    historia: 'Três camponesas recolhem espigas deixadas na colheita, um direito dos mais pobres. Ao fundo, a fartura dos proprietários contrasta com a curvatura delas.',
    contextoHistorico: 'Depois da Revolução de 1848, a França discutia a condição dos trabalhadores.',
    contextoFilosofico: 'O Realismo dignifica o trabalho humilde e denuncia a desigualdade.',
    contextoSocial: 'A elite criticou a obra como "propaganda socialista"; hoje é vista como testemunho social.',
    curiosidade: 'Van Gogh admirava Millet e copiou várias de suas obras.',
  },
  'angelus': {
    titulo: 'O Ângelus', artista: 'Jean-François Millet', ano: '1859', movimento: 'Realismo (Escola de Barbizon)', localAtual: 'Museu d\'Orsay, Paris',
    historia: 'Um casal de camponeses interrompe o trabalho para rezar o Ângelus, ao toque do sino ao entardecer. O silêncio do campo é o assunto.',
    contextoHistorico: 'A França rural ainda era profundamente católica, apesar da industrialização.',
    contextoFilosofico: 'A fé e o trabalho aparecem como partes da mesma dignidade.',
    contextoSocial: 'A obra virou ícone popular e foi reproduzida em milhões de estampas.',
    curiosidade: 'Salvador Dalí dedicou-se a analisar o quadro e escreveu um livro sobre ele.',
  },
  'campo-de-papoulas': {
    titulo: 'Campo de Papoulas', artista: 'Claude Monet', ano: '1873', movimento: 'Impressionismo', localAtual: 'Museu d\'Orsay, Paris',
    historia: 'Uma mulher com sombrinha e uma criança caminham num campo de papoulas perto de Argenteuil. As manchas vermelhas quase vibram contra o verde.',
    contextoHistorico: 'A França se reconstruía depois de 1870, e o trem levava artistas ao campo.',
    contextoFilosofico: 'A observação direta da natureza substituiu a composição de ateliê.',
    contextoSocial: 'Cenas de lazer burguês eram novidade como tema de arte.',
    curiosidade: 'É provável que as figuras sejam a esposa de Monet, Camille, e o filho Jean, repetidos na mesma cena.',
  },
  'mulher-com-sombrinha': {
    titulo: 'Mulher com Sombrinha', artista: 'Claude Monet', ano: '1875', movimento: 'Impressionismo', localAtual: 'National Gallery of Art, Washington',
    historia: 'Camille Monet e o filho Jean em uma colina ventosa, vistos de baixo, com nuvens rápidas ao fundo. A obra parece um instante flagrado, não um pose.',
    contextoHistorico: 'Os impressionistas expunham por conta própria e enfrentavam a crítica.',
    contextoFilosofico: 'O instante é mais importante que o assunto: luz e vento são os verdadeiros protagonistas.',
    contextoSocial: 'A família do artista, pouco abastada, aparece como tema íntimo.',
    curiosidade: 'Monet pintou uma versão parecida, com o rosto da mulher em destaque, mais de dez anos depois.',
  },
  'catedral-de-rouen': {
    titulo: 'Catedral de Rouen', artista: 'Claude Monet', ano: '1894', movimento: 'Impressionismo', localAtual: 'Museu d\'Orsay, Paris (uma das cerca de 30 versões)',
    historia: 'Monet pintou a mesma fachada gótica em mais de 30 telas, em diferentes horas e climas. A pedra se dissolve em cor e luz.',
    contextoHistorico: 'A França vivia estabilidade e progresso, e a fotografia se popularizava.',
    contextoFilosofico: 'A obra investiga o tempo e a percepção: nada é visto duas vezes da mesma forma.',
    contextoSocial: 'O artista, já reconhecido, alugava salas em frente à catedral para pintar.',
    curiosidade: 'Ele trabalhava em várias telas ao mesmo tempo, trocando conforme a luz mudava.',
  },
  'jogadores-de-cartas': {
    titulo: 'Os Jogadores de Cartas', artista: 'Paul Cézanne', ano: '1895', movimento: 'Pós-impressionismo', localAtual: 'Museu d\'Orsay, Paris (uma das cinco versões)',
    historia: 'Dois camponeses jogam cartas em silêncio, absortos, numa composição de formas sólidas e equilibradas. Cézanne a pintou em cinco versões.',
    contextoHistorico: 'A França provinciana de Aix-en-Provence contrastava com a agitação de Paris.',
    contextoFilosofico: 'Cézanne buscava a estrutura por trás das aparências, tratando a natureza "pelo cilindro, a esfera e o cone".',
    contextoSocial: 'Os modelos eram trabalhadores da propriedade da família, e a cena não é anedótica, mas quase monumental.',
    curiosidade: 'Uma das versões foi comprada em 2011 pelo Catar por uma cifra estimada em 250 milhões de dólares.',
  },
  'montanha-sainte-victoire': {
    titulo: 'A Montanha Sainte-Victoire', artista: 'Paul Cézanne', ano: '1904', movimento: 'Pós-impressionismo', localAtual: 'Museu de Arte da Filadélfia (uma das versões)',
    historia: 'Cézanne pintou a montanha de sua terra, perto de Aix-en-Provence, dezenas de vezes. Ao longo dos anos, as formas viraram blocos de cor cada vez mais estruturados.',
    contextoHistorico: 'A França do início do século XX preparava o terreno para as vanguardas.',
    contextoFilosofico: 'Cézanne foi chamado "pai da arte moderna": abriu o caminho para o Cubismo.',
    contextoSocial: 'Vivia recluso e foi reconhecido só nos últimos anos da vida.',
    curiosidade: 'Picasso e Matisse disseram que Cézanne foi "o pai de todos nós".',
  },
  'campo-de-trigo-corvos': {
    titulo: 'Campo de Trigo com Corvos', artista: 'Vincent van Gogh', ano: '1890', movimento: 'Pós-impressionismo', localAtual: 'Museu Van Gogh, Amsterdã',
    historia: 'Um céu carregado sobre um trigal em Auvers-sur-Oise, com caminhos que levam a lugar nenhum. Foi pintada nas últimas semanas de vida do artista.',
    contextoHistorico: 'A Europa vivia rápida mudança social, e o campo virava refúgio de artistas.',
    contextoFilosofico: 'A tela transmite solidão e força emocional, o núcleo do Expressionismo que viria.',
    contextoSocial: 'Van Gogh morreu em julho de 1890, aos 37 anos, quase desconhecido.',
    curiosidade: 'Não é comprovado que seja sua última obra, apesar de muitas vezes ser apontada assim.',
  },
  'autorretrato-van-gogh': {
    titulo: 'Autorretrato com Orelha Enfaixada', artista: 'Vincent van Gogh', ano: '1889', movimento: 'Pós-impressionismo', localAtual: 'Instituto Courtauld, Londres',
    historia: 'Pintado semanas depois de cortar parte da própria orelha, em dezembro de 1888. Van Gogh se retrata sereno, de gorro e casaco, com um cavalete e uma gravura japonesa ao fundo.',
    contextoHistorico: 'A gravura japonesa influenciava muitos artistas europeus.',
    contextoFilosofico: 'O autorretrato como investigação de si, sem idealização.',
    contextoSocial: 'A saúde mental era pouco compreendida, e o pintor era visto com receio pela vizinhança de Arles.',
    curiosidade: 'Ele fez este autorretrato e outro semelhante, com cachimbo, logo depois do episódio.',
  },
  'ofelia': {
    titulo: 'Ofélia', artista: 'John Everett Millais', ano: '1852', movimento: 'Pré-rafaelita', localAtual: 'Tate Britain, Londres',
    historia: 'A personagem de "Hamlet" flutua num rio cercado de flores, cantando, pouco antes de se afogar. Cada flor tem um significado simbólico.',
    contextoHistorico: 'A Inglaterra vitoriana vivia o auge do Império e da industrialização.',
    contextoFilosofico: 'Os Pré-rafaelitas queriam voltar à verdade da natureza, em reação à arte acadêmica.',
    contextoSocial: 'A modelo, Elizabeth Siddal, posou dentro de uma banheira e ficou doente de frio.',
    curiosidade: 'Millais pintou a paisagem ao ar livre durante meses, à beira do rio Hogsmill.',
  },
  'mucha-job': {
    titulo: 'Cartaz Job', artista: 'Alphonse Mucha', ano: '1896', movimento: 'Art Nouveau', localAtual: 'Coleções de museus de arte gráfica em vários países',
    historia: 'Cartaz publicitário de papel de cigarro, com uma mulher de cabelos longos e fumaça em curvas. O estilo de Mucha definiu a imagem do Art Nouveau.',
    contextoHistorico: 'A litografia colorida popularizou o cartaz nas ruas de Paris.',
    contextoFilosofico: 'O Art Nouveau buscava unir arte e vida cotidiana, dissolvendo a fronteira entre "arte maior" e "aplicada".',
    contextoSocial: 'A publicidade moderna nascia, e a arte chegava ao grande público pela rua.',
    curiosidade: 'Mucha ficou famoso da noite para o dia com um cartaz para a atriz Sarah Bernhardt.',
  },
  'ameixeiras-kameido': {
    titulo: 'Jardim de Ameixeiras em Kameido', artista: 'Utagawa Hiroshige', ano: '1857', movimento: 'Ukiyo-e (estampa japonesa)', localAtual: 'Coleções de museus em vários países',
    historia: 'Um galho de ameixeira em primeiro plano corta a cena e revela um jardim visto de perto. Faz parte de "Cem Vistas Famosas de Edo".',
    contextoHistorico: 'No Japão Edo, a floração das ameixeiras anunciava a primavera e era festejada.',
    contextoFilosofico: 'A contemplação da natureza sazonal é central na cultura japonesa.',
    contextoSocial: 'Passeios a jardins famosos eram lazer popular das classes urbanas.',
    curiosidade: 'Van Gogh também copiou esta estampa, em 1887.',
  },
  'batalha-guararapes': {
    titulo: 'A Batalha dos Guararapes', artista: 'Victor Meirelles', ano: '1879', movimento: 'Academicismo romântico', localAtual: 'Museu Nacional de Belas Artes, Rio de Janeiro',
    historia: 'A tela retrata a vitória de forças luso-brasileiras sobre os holandeses em Pernambuco, em 1648–49. É considerada uma das maiores pinturas de batalha do país.',
    contextoHistorico: 'O Brasil colonial disputava território com holandeses, que ocuparam o Nordeste no século XVII.',
    contextoFilosofico: 'O Romantismo exaltava os mitos de origem nacional.',
    contextoSocial: 'A obra foi encomendada pelo Império para celebrar a unidade entre brancos, negros e indígenas na luta, ideia usada como símbolo de nação.',
    curiosidade: 'O quadro tem mais de 9 metros de largura e ocupa uma sala inteira do museu.',
  },
  'tempestade-de-neve': {
    titulo: 'Tempestade de Neve: Barco a Vapor', artista: 'J. M. W. Turner', ano: '1842', movimento: 'Romantismo', localAtual: 'Tate Britain, Londres',
    historia: 'Um vapor luta contra o mar revolto e a neve, em um turbilhão de luz e cor. Turner disse ter se amarrado ao mastro por quatro horas para vivenciar a tempestade.',
    contextoHistorico: 'A navegação a vapor transformava o comércio e as viagens.',
    contextoFilosofico: 'O sublime: a força da natureza esmaga o humano e ao mesmo tempo o encanta.',
    contextoSocial: 'Um crítico chamou a obra de "sabão e cal", e Turner respondeu que não se importava, pois pintava o que sentiu.',
    curiosidade: 'Muitos veem em Turner um precursor da pintura abstrata.',
  },
  'vista-de-delft': {
    titulo: 'Vista de Delft', artista: 'Johannes Vermeer', ano: 'c. 1660', movimento: 'Barroco holandês', localAtual: 'Mauritshuis, Haia',
    historia: 'A cidade natal de Vermeer, vista do outro lado do rio sob nuvens que deixam a luz cair em manchas. Ele usou pontos de luz que lembram gotículas na superfície.',
    contextoHistorico: 'A Holanda estava no auge econômico, mas ameaçada por guerras contra Inglaterra e França.',
    contextoFilosofico: 'A observação científica da luz aproximava a pintura da ótica.',
    contextoSocial: 'Delft, cidade de artesãos e comerciantes, conhecia a cerâmica azul e branca.',
    curiosidade: 'O escritor Marcel Proust chamou a obra de "o mais belo quadro do mundo".',
  },
  'licao-de-anatomia': {
    titulo: 'A Lição de Anatomia do Dr. Tulp', artista: 'Rembrandt van Rijn', ano: '1632', movimento: 'Barroco holandês', localAtual: 'Mauritshuis, Haia',
    historia: 'Dr. Nicolaes Tulp dissecando um braço diante de colegas da guilda dos cirurgiões de Amsterdã. Foi o primeiro grande retrato de grupo de Rembrandt, ainda com 26 anos.',
    contextoHistorico: 'Amsterdã tornava-se um polo científico: dissecações públicas eram eventos anuais.',
    contextoFilosofico: 'A ciência empírica e a curiosidade sobre o corpo humano ganhavam força.',
    contextoSocial: 'Os retratados pagavam pela inclusão; a composição dá a cada um seu lugar.',
    curiosidade: 'O cadáver era o de um criminoso executado, e o braço mostra tendões com precisão anatômica notável.',
  },
  'arvore-da-vida': {
    titulo: 'A Árvore da Vida', artista: 'Gustav Klimt', ano: '1909', movimento: 'Art Nouveau / Secessão Vienense', localAtual: 'Museu de Artes Aplicadas (MAK), Viena',
    historia: 'Espirais douradas de uma árvore simbolizam a ligação entre vida e morte. O painel fazia parte do friso do Palácio Stoclet, em Bruxelas.',
    contextoHistorico: 'A Europa às vésperas da Primeira Guerra vivia a última grande luz do Art Nouveau.',
    contextoFilosofico: 'Um símbolo universal de conexão entre céu, terra e o ciclo da vida.',
    contextoSocial: 'O friso foi encomendado por um industrial belga, mostrando o mecenato da nova burguesia.',
    curiosidade: 'É considerada uma das obras decorativas mais luxuosas do Art Nouveau.',
  },
  'dr-gachet': {
    titulo: 'Retrato do Dr. Gachet', artista: 'Vincent van Gogh', ano: '1890', movimento: 'Pós-impressionismo', localAtual: 'Versões no Museu d\'Orsay (Paris) e em coleção particular',
    historia: 'O médico que cuidou de Van Gogh em Auvers-sur-Oise aparece de cabeça apoiada na mão, com olhar melancólico. Van Gogh disse ter pintado "a expressão de tristeza do nosso tempo".',
    contextoHistorico: 'Em 1890, Van Gogh estava a poucas semanas do fim da vida.',
    contextoFilosofico: 'A tela mostra a melancolia como traço de uma sensibilidade moderna.',
    contextoSocial: 'Gachet, médico e amigo de artistas, era ele mesmo colecionador e gravador.',
    curiosidade: 'Uma versão foi vendida em 1990 por mais de 82 milhões de dólares, o maior preço de arte da época.',
  },
};
