// Peca ou leilao sem foto enviada: o BACKEND escolhe uma obra do acervo (arquivos em
// FrontEnd/public/acervo), sempre a mesma para o mesmo id. A tela so exibe o caminho
const OBRAS_DO_ACERVO = [
  'noite-estrelada.jpg',
  'moca-brinco-perola.jpg',
  'impressao-nascer-do-sol.jpg',
  'girassois.jpg',
  'grande-onda.jpg',
  'nascimento-venus.jpg',
  'o-beijo.jpg',
  'autorretrato-rembrandt.jpg',
  'leiteira.jpg',
  'domingo-grande-jatte.jpg',
  'mona-lisa.jpg',
  'venus-de-milo.jpg',
  'las-meninas.jpg',
  'ronda-da-noite.jpg',
  'o-grito.jpg',
  'viajante-nevoeiro.jpg',
  'ninfeias.jpg',
  'jardim-das-delicias.jpg',
  'casal-arnolfini.jpg',
  'ultima-ceia.jpg',
  'carroca-de-feno.jpg',
  'liberdade-guiando-povo.jpg',
  'almoco-remadores.jpg',
  'bar-folies-bergere.jpg',
  'olimpia.jpg',
  'terraco-cafe-noite.jpg',
  'quarto-arles.jpg',
  'madame-x.jpg',
  'primavera.jpg',
  'escola-de-atenas.jpg',
  'criacao-de-adao.jpg',
  'arte-da-pintura.jpg',
  'judite-klimt.jpg',
  'adele-bloch-bauer.jpg',
  'caipira-picando-fumo.jpg',
  'independencia-ou-morte.jpg',
  'primeira-missa.jpg',
  'fuji-vermelho.jpg',
  'chuva-ponte-ohashi.jpg',
  'temerario.jpg',
  'judite-caravaggio.jpg',
  'tres-de-maio.jpg',
  'menino-azul.jpg',
  'grande-odalisca.jpg',
  'mae-de-whistler.jpg',
  'cigana-adormecida.jpg',
  'baile-moulin.jpg',
  'cacadores-na-neve.jpg',
  'torre-de-babel.jpg',
  'embaixadores.jpg',
  'venus-de-urbino.jpg',
  'jangada-da-medusa.jpg',
  'respigadoras.jpg',
  'angelus.jpg',
  'campo-de-papoulas.jpg',
  'mulher-com-sombrinha.jpg',
  'catedral-de-rouen.jpg',
  'jogadores-de-cartas.jpg',
  'montanha-sainte-victoire.jpg',
  'campo-de-trigo-corvos.jpg',
  'autorretrato-van-gogh.jpg',
  'ofelia.jpg',
  'mucha-job.jpg',
  'ameixeiras-kameido.jpg',
  'batalha-guararapes.jpg',
  'tempestade-de-neve.jpg',
  'vista-de-delft.jpg',
  'licao-de-anatomia.jpg',
  'arvore-da-vida.jpg',
  'dr-gachet.jpg',
];

export function capaPadrao(id: string): string {
  let soma = 0;
  for (const c of id) soma = (soma * 31 + c.charCodeAt(0)) >>> 0;
  return `acervo/${OBRAS_DO_ACERVO[soma % OBRAS_DO_ACERVO.length]}`;
}
